name: Deploy to prod from master branch
on:
  push:
    branches: [master]
concurrency:
  group: js-wallet-prod-deploy
  cancel-in-progress: true
jobs:
  e2e-tests-local:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - name: checkout JsWallet
        uses: actions/checkout@v2
      - name: checkout web3t
        uses: actions/checkout@v2
        with:
          repository: velas/web3t
          path: .compiled-ssr/web3t
          ref: master
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: install web3t modules
        working-directory: .compiled-ssr/web3t
        run: npm i
      - name: install lsxc
        run: npm i lsxc -g --unsafe-perm
      - name: copy web3 side by side to wallet
        working-directory: ../
        run: rm -rf JsWallet/.compiled-ssr/web3t/.git/objects/ && mkdir -p web3t/ && cp -pr JsWallet/.compiled-ssr/web3t/ ./
      - name: delete wallet build cache
        working-directory: ./
        run: rm -rf ./.compiled
      - name: run wallet
        working-directory: ./
        run: |
          npm run wallet-start:no-watch &
          echo '- - - - - Wallet is started but it takes till 30 seconds to be up - - - - -'
      - name: install modules required for testrun
        run: npm i
      - name: clean previous test results
        run: rm -rf ./test-results/
      - name: blockchain health check
        run: CI=true LOG_LEVEL=debug npm run blockchain-health-check
      - name: balances api health check
        run: CI=true npm run balances-api-health-check
      - name: run tests
        run: CI=true LOG_LEVEL=debug npm run test
      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            e2e/test-results/
          retention-days: 7

  docker-build-push:
    name: Build and push (prod)
    runs-on: ubuntu-latest
    # TODO: if tests will not have invalid fail (fail when should pass) - uncomment next line
    # needs: e2e-tests-local
    outputs:
      repository: ${{ steps.build.outputs.repository }}
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: checkout
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to AWS ECR
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: velas-wallet
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --no-cache .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=repository::$ECR_REPOSITORY"
          echo "::set-output name=image_tag::$IMAGE_TAG"
  deploy:
    name: Deploy to testnet via Helmfile
    runs-on: deployer
    needs: docker-build-push
    container:
      image: cablespaghetti/helmfile-docker:3.5.4
    steps:     
      - name: Configure AWS credentials
        id: checkout
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.9.0
        with:
          helmfile-version: "v0.142.0"
      - name: Check out velas-infra
        uses: actions/checkout@master
        with:
          repository: velas/velas-infra
          ssh-key: ${{ secrets.INFRA_SSH_KEY }}
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA_AWS_RAW }}
          context: "eks_prod-prod"
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.1.0
      - name: Deploy via helmfile
        id: deploy
        env:
          ECR_REPOSITORY: ${{ needs.docker-build-push.outputs.repository }}
          IMAGE_TAG: ${{ needs.docker-build-push.outputs.image_tag }}
          ECR_REGION: ${{ secrets.AWS_REGION }}
        run: |
          if [ `helm plugin list|grep diff|wc -l` -eq '0' ]; then helm plugin install https://github.com/databus23/helm-diff ; fi
          if [ ${GITHUB_REF##*/} = 'master' ]; then NAMESPACE=default; fi
          cd deploy
          account_id=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .accountId)
          ECR_REGISTRY=${account_id}.dkr.ecr.${ECR_REGION}.amazonaws.com
          helmfile -e prod -l namespace=default,name=velas-wallet apply  --set image.tag=$IMAGE_TAG,image.repository=$ECR_REGISTRY/$ECR_REPOSITORY --skip-deps
  e2e-tests-prod:
    needs: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e
    steps:
      - name: checkout JsWallet
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: install npm modules
        run: npm i
      - name: clean previous test results
        run: rm -rf ./test-results/
      - name: run tests
        run: CI=true LOG_LEVEL=debug ENVIRONMENT=prod NETWORK=testnet npm test
      - name: upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: e2e/test-results/
          retention-days: 7
